# Premier League Match Prediction

## Exploratory Data Analysis (EDA)

### Project Overview

This project aims to identify the most impactful factors in predicting Premier League match outcomes.

The dataset consists of 10 seasons of Premier League match data containing match results and in game statistics.

### Objectives

- Understand the structure of the dataset
- Assess data quality
- Explore target variable distributions
- Investigate home-field advantage
- Analyze scoring patterns
- Compare team performance
- Identify potential predictive features
- Generate insights for feature engineering

In [5]:
from pathlib import Path

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

DATA_PATH = Path("../data/processed/epl_combined_cleaned.csv")

df = pd.read_csv(DATA_PATH)

print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 3800
Columns: 25

# 1. Dataset Overview

First, we examine the structure of the dataset to understand the available features and verify that the cleaning process was successful.

In [ ]:
df.head()

,Season,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,Referee,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
0,2016_2017,E0,2016-08-13,NaN,Burnley,Swansea,0,1,A,0,0,D,J Moss,10,17,3,9,10,14,7,4,3,2,0,0
1,2016_2017,E0,2016-08-13,NaN,Crystal Palace,West Brom,0,1,A,0,0,D,C Pawson,14,13,4,3,12,15,3,6,2,2,0,0
2,2016_2017,E0,2016-08-13,NaN,Everton,Tottenham,1,1,D,1,0,H,M Atkinson,12,13,6,4,10,14,5,6,0,0,0,0
3,2016_2017,E0,2016-08-13,NaN,Hull,Leicester,2,1,H,1,0,H,M Dean,14,18,5,5,8,17,5,3,2,2,0,0
4,2016_2017,E0,2016-08-13,NaN,Man City,Sunderland,2,1,H,1,0,H,R Madley,16,7,4,3,11,14,9,6,1,2,0,0

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Data columns (total 25 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Season    3800 non-null   str
 1   Div       3800 non-null   str
 2   Date      3800 non-null   str
 3   Time      2660 non-null   str
 4   HomeTeam  3800 non-null   str
 5   AwayTeam  3800 non-null   str
 6   FTHG      3800 non-null   int64
 7   FTAG      3800 non-null   int64
 8   FTR       3800 non-null   str
 9   HTHG      3800 non-null   int64
 10  HTAG      3800 non-null   int64
 11  HTR       3800 non-null   str
 12  Referee   3800 non-null   str
 13  HS        3800 non-null   int64
 14  AS        3800 non-null   int64
 15  HST       3800 non-null   int64
 16  AST       3800 non-null   int64
 17  HF        3800 non-null   int64
 18  AF        3800 non-null   int64
 19  HC        3800 non-null   int64
 20  AC        3800 non-null   int64
 21  HY        3800 non-null   int64
 22  AY        3800 non-null   int64
 23  HR        3800 non-null   int64
 24  AR        3800 non-null   int64
dtypes: int64(16), str(9)
memory usage: 742.3 KB

In [11]:
df.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,HC,AC,HY,AY,HR,AR
count,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000,3800.000000
mean,1.555263,1.279737,0.697895,0.564211,13.867105,11.480263,4.768158,4.023421,10.598158,10.868158,5.664474,4.687632,1.656579,1.850000,0.053947,0.061053
std,1.313304,1.207771,0.847582,0.780172,5.685582,5.060168,2.618839,2.362564,3.426335,3.562880,3.060554,2.796334,1.271598,1.311911,0.236196,0.244893
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,10.000000,8.000000,3.000000,2.000000,8.000000,8.000000,3.000000,3.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,0.000000,13.000000,11.000000,4.000000,4.000000,10.000000,11.000000,5.000000,4.000000,2.000000,2.000000,0.000000,0.000000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,15.000000,6.000000,5.000000,13.000000,13.000000,8.000000,6.000000,2.000000,3.000000,0.000000,0.000000
max,9.000000,9.000000,5.000000,5.000000,37.000000,37.000000,17.000000,15.000000,24.000000,26.000000,19.000000,19.000000,7.000000,8.000000,2.000000,2.000000

In [12]:
num_matches = len(df)

num_seasons = df["Season"].nunique()

teams = set(df["HomeTeam"]).union(set(df["AwayTeam"]))

num_teams = len(teams)

print(f"Matches: {num_matches}")
print(f"Seasons: {num_seasons}")
print(f"Teams: {num_teams}")

Matches: 3800
Seasons: 10
Teams: 34

# 2. Data Quality Assessment

Before modeling, it is important to understand whether any missing values or duplicate records exist.